// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFL0OYkhRaQas4KfwQtplHzsFUmAvtGPo',
    appId: '1:330068600929:web:be8ee4ee20d72acb1fe220',
    messagingSenderId: '330068600929',
    projectId: 'focus-d65bf',
    authDomain: 'focus-d65bf.firebaseapp.com',
    databaseURL: 'https://focus-d65bf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'focus-d65bf.firebasestorage.app',
    measurementId: 'G-63EG4EHD4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAe8BN1RS5GTfeYgL-JtJAHIgyXgz3AcM',
    appId: '1:330068600929:android:caddbcfa0ce6fd7b1fe220',
    messagingSenderId: '330068600929',
    projectId: 'focus-d65bf',
    databaseURL: 'https://focus-d65bf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'focus-d65bf.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFL0OYkhRaQas4KfwQtplHzsFUmAvtGPo',
    appId: '1:330068600929:web:c42b40db21a1cde81fe220',
    messagingSenderId: '330068600929',
    projectId: 'focus-d65bf',
    authDomain: 'focus-d65bf.firebaseapp.com',
    databaseURL: 'https://focus-d65bf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'focus-d65bf.firebasestorage.app',
    measurementId: 'G-ZCW5H58TR7',
  );
}
